
GET http://localhost:3000/

###

GET http://localhost:3000/guitars

###

GET http://localhost:3000/guitars/1

###

POST http://localhost:3000/guitars
Content-Type: application/json

{
    "id": 4,
    "name": "Gibson",
    "color": "Blue",
    "price":"8590",
    "type":"electric"
}

###

PUT http://localhost:3000/guitars/1
Content-Type: application/json

{
    "id":1,
    "name":"Fender",
    "color":"Black and white",
    "price":"4955",
    "type":"electric"
}

###

DELETE http://localhost:3000/guitars/delete/2
Content-Type: application/json

###